### ISSUE TITLE
password is in clear text

### ISSUE THREAD

**Issue by mgalm** [bluecatlabs/rundeck-bluecat-gateway-plugin#3]
if one creates a new definition the credentials are in cleartext which is bad for passwords

![credentials](https://user-images.githubusercontent.com/32574456/50337349-2089de80-0511-11e9-9adf-f38552bf47fe.png)

**Comment by xiax** [comment]
So in the job options for rundeck there should be the ability to create an encrypted password. Here is the link to a demo the rundeck guys did about it.

https://www.google.com/amp/s/www.rundeck.com/blog/use-rundecks-key-storage-to-manage-passwords-and-secrets%3fhs_amp=true

**Comment by sharma-anshul** [comment]
Marking this issue closed.
